export const MockFarmers = {
  smallFarmer: {
    state: 'Punjab',
    district: 'Amritsar',
    village: 'Jassa',
    landSize: 2.5,
    landUnit: 'acres',
    cropType: 'Wheat',
    irrigationType: 'tube-well',
    soilType: 'Alluvial',
    annualIncome: 180000,
    loanAmount: 50000,
    farmingExperience: 8,
    livestock: ['cow']
  },
  marginalFarmer: {
    state: 'Rajasthan',
    district: 'Jodhpur',
    village: 'Mandore',
    landSize: 1.2,
    landUnit: 'acres',
    cropType: 'Cotton',
    irrigationType: 'drip',
    soilType: 'Sandy',
    annualIncome: 90000,
    loanAmount: 220000,
    farmingExperience: 5,
    livestock: ['goat', 'sheep']
  },
  mediumFarmer: {
    state: 'Maharashtra',
    district: 'Nashik',
    village: 'Pimpalgaon',
    landSize: 7.5,
    landUnit: 'acres',
    cropType: 'Sugarcane',
    irrigationType: 'sprinkler',
    soilType: 'Black',
    annualIncome: 450000,
    loanAmount: 300000,
    farmingExperience: 18,
    livestock: ['buffalo']
  },
  largeFarmer: {
    state: 'Kerala',
    district: 'Wayanad',
    village: 'Kalpetta',
    landSize: 18.0,
    landUnit: 'acres',
    cropType: 'Rice',
    irrigationType: 'canal',
    soilType: 'Clayey',
    annualIncome: 950000,
    loanAmount: 150000,
    farmingExperience: 25,
    livestock: ['cow', 'buffalo', 'poultry']
  },
  riceFarmer: {
    state: 'Kerala',
    district: 'Palakkad',
    village: 'Chittur',
    landSize: 5.0,
    landUnit: 'acres',
    cropType: 'Rice',
    irrigationType: 'canal',
    soilType: 'Clayey',
    annualIncome: 250000,
    loanAmount: 80000,
    farmingExperience: 15,
    livestock: ['cow']
  },
  wheatFarmer: {
    state: 'Punjab',
    district: 'Ludhiana',
    village: 'Baddowal',
    landSize: 8.0,
    landUnit: 'acres',
    cropType: 'Wheat',
    irrigationType: 'tube-well',
    soilType: 'Alluvial',
    annualIncome: 500000,
    loanAmount: 200000,
    farmingExperience: 20,
    livestock: ['buffalo', 'cow']
  },
  sugarcaneFarmer: {
    state: 'Maharashtra',
    district: 'Pune',
    village: 'Baramati',
    landSize: 10.0,
    landUnit: 'acres',
    cropType: 'Sugarcane',
    irrigationType: 'drip',
    soilType: 'Black',
    annualIncome: 700000,
    loanAmount: 400000,
    farmingExperience: 22,
    livestock: ['buffalo']
  },
  vegetableFarmer: {
    state: 'Gujarat',
    district: 'Anand',
    village: 'Karamsad',
    landSize: 3.5,
    landUnit: 'acres',
    cropType: 'Cotton',
    irrigationType: 'sprinkler',
    soilType: 'Sandy',
    annualIncome: 220000,
    loanAmount: 180000,
    farmingExperience: 6,
    livestock: ['cow']
  }
};
